### ISSUE TITLE
Use env variables for sensitive data

### ISSUE THREAD

**Issue by pulkitsinghal** [rahulrsingh09/AngularConcepts#5]
> Is it ok to have the values visible?
`AngularConcepts/src/app/shared/firebase.config.ts`

**Comment by rahulrsingh09** [comment]
@pulkitsinghal Yup i will need to fix that based on the build as on now this is not the actual config file i am loading this is more like a testing build file i keep a dev firebase account and one as fixed. The original is not posted , i just replace those data at the time of ```ng build --prod```.

But yes it this is something i will correct asap .

**Comment by rahulrsingh09** [comment]
Fixed the issue now loading all the configuration by the enviornment

**Comment by rahulrsingh09** [comment]
Fixed the issue now loading all the configuration by the environment
